### ISSUE TITLE
Add note to documentation on how to view generated assembly?

### ISSUE THREAD

**Issue by bcampbell** [llvm-mos/llvm-mos-sdk#111]
Is there an easy way to see readable 6502 code from the compiler?
`mos-<whatever>-clang -S foo.c` outputs something I'm sure I could learn to read, but it'd be nice to see the actual 6502 output, with symbol names and all (ideally with line number info, to link back to the original source).

Background:
I've been tinkering, making up a small arcade game using mos-cx16-clang and I've run into what I _think_ is a code generation problem (I'm seeing data being corrupted by other parts of my code). And I'd like to confirm that it's not just something stupid I'm doing!
All my attempts to pare the code down into a nice simple reproduction case fail - the problem just moves around and disappears when I do so.
(The same code runs fine compiled for Linux (stock distro gcc) and Nintendo DS (devkitpro gcc). And I've been pretty careful to be mindful of 8-bit limits. I'm happy to send it to anyone who's interested in taking a peek at it).
Or are there some clever debugging ideas I should try out?

**Comment by bcampbell** [comment]
At one point I obviously found something in the docs which _kind_ of does what I want - I left myself a note in my Makefile:
`llvm-objdump -dSr game.prg.elf >game.s`
This is soooo close to what I want. It gives source code in comments, followed by generated asm... but the asm is all using absolute addresses, so it's very hard to track which variables are being fiddled with...

**Comment by johnwbyrd** [comment]
Why not the line from README.md:

`mos-c64-clang -Os -o hello.s -Wl,--lto-emit-asm <install_dir>/examples/hello-putchar.c`

**Comment by bcampbell** [comment]
> Why not the line from README.md:
> 
> `mos-c64-clang -Os -o hello.s -Wl,--lto-emit-asm <install_dir>/examples/hello-putchar.c`

I did try that, but all the symbols seem to have been anonymised by that point, so you just get output where all the functions look like this:
```
	.section	.text.__ashrqi3,"ax",@progbits
	.globl	__ashrqi3                       ; -- Begin function __ashrqi3
	.type	__ashrqi3,@function
__ashrqi3:                              ; @__ashrqi3
.Lfunc_begin8:
; %bb.0:
	jmp	.LBB8_2
.LBB8_1:                                ;   in Loop: Header=BB8_2 Depth=1
	dex
	cmp	#128
	ror
.LBB8_2:                                ; =>This Inner Loop Header: Depth=1
	cpx	#0
	bne	.LBB8_1
; %bb.3:
	rts
.Lfunc_end8:
	.size	__ashrqi3, .Lfunc_end8-__ashrqi3
                                        ; -- End function
```
etc...
Unless there's something I'm missing which preserves the symbols?

Maybe I just need to use `-S` and learn to read the intermediate code.

I do recognise the sheer gymnastics that must be happening to provide local variables without using the stack... so maybe it's just not realistic to expect readable symbols to survive such contortions!
But being able to get cleanly-formatted 6502 asm with symbols out would be Nice to Have (tm) - both from a debugging point of view, and a starting-place-for-hand-optimised-asm point of view. I can wish, can't I? ;-)

**Comment by mysterymath** [comment]
The closest thing that exists to what you want is to build with debug symbols, then use the objdump options that reference those. It adds a lot of noise, but that noise does contain the best available mappings back to the original source (those gdb/lldb use).

You may want to try playing around with upstream LLVM; we have the same limitations, and we don't really have the bandwidth to add major features to upstream.

Accordingly, I'll close this one; we can't do much better than the modern LLVM status quo.

**Comment by bcampbell** [comment]
Thanks, figured it was worth asking. I'll keep poking about and see if I can think up anything.
(And thanks for working on llvm-mos in the first place - it's really quite shockingly good : )
