### ISSUE TITLE
Issue on PCE rom generation

### ISSUE THREAD

**Issue by lunoka** [llvm-mos/llvm-mos-sdk#138]
Hello/

I've downloaded & extracted the compiler & sdk. Launched the mos-pce-clang command on examples putchar.c & color-cycle.c for PCE. Roms are generated but only a black screen appears when I launch them on Mesen 2 or Bizhawk emulators.

Have I forgotten something on the intial setup?

Btw, my OS is linux mint, I haven't tried on Windows.

**Comment by mysterymath** [comment]
@asiekierka might know more, but I'll try to reproduce this with a fresh install in the morning

**Comment by asiekierka** [comment]
This is a regression introduced in v1.2.0+; v1.1.0 should work fine, for the time being.
