### ISSUE TITLE
Can't compile putchar.c example on pce & nes-mmc1 platform

### ISSUE THREAD

**Issue by lunoka** [llvm-mos/llvm-mos-sdk#141]
Hello,

I get this if I try to compile for pce or nes-mmc1 :

/llvm-mos/bin$ ./mos-pce-clang -Os -o hello.pce ../examples/hello-putchar.c
ld.lld: error: undefined symbol: __putchar
>>> referenced by ld-temp.o
>>>               lto.tmp:(main)
mos-pce-clang: error: ld.lld command failed with exit code 1 (use -v to see invocation)

On the other hand it works for C64 platform for example. Did I use wrong options ?

Fresh download of compiler & sdk by the way ( linux ).

**Comment by mysterymath** [comment]
Those targets don't have a built-in operating system to which something like "putchar" could be directed, while the c64 does: its KERNAL. Unlike cc65, we generally don't attempt to build additional OS-like functionality into the SDK; instead, the goal is to expose whatever functionality is intrinsically present in the target.

**Comment by mysterymath** [comment]
These targets don't support putchar, since there's no underlying OS to which such an abstract operation could be directed. In the past we've been open to including screen drivers for such targets, but they aren't required, and it seems out of scope for the SDK to include e.g. a character set ROM.

**Comment by mysterymath** [comment]
These targets don't support putchar, since there's no underlying OS to which such an abstract operation could be directed. In the past we've been open to including screen drivers for such targets, but they aren't required, and it seems out of scope for the SDK to include e.g. a character set ROM.
