### ISSUE TITLE
Commander X16 PETSCII character set

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos-sdk#160]
The Commander X16 supports PETSCII, but there is no official Unicode mapping for this target. We should go through and compare it to the existing Commodore targets to produce an accurate Unicode mapping. Hopefully this is identical to that of the Commodore 64; if not, the mapping should be given as a table on the wiki. This should also include the ISO character set; llvm-mos's execution character set is UTF-8, which is a multibyte encoding, so a user-defined literal for this is still very useful, even though the mapping is trivial.

**Comment by asiekierka** [comment]
The Commander X16's changes relative to the Commodore 64 are documented here:

https://github.com/commanderx16/x16-rom/blob/master/charset/petscii.s

In addition, an additional character set based on ISO-8859-15 is supported, documented here:

https://github.com/commanderx16/x16-rom/blob/master/charset/iso-8859-15.s

This is referred to as "ISO mode" in the changelogs.

**Comment by asiekierka** [comment]
The Unicode mapping for ISO-8859-15 in a familiar format is available here, but it doesn't include the CX16 reverse video additions:

https://unicode.org/Public/MAPPINGS/ISO8859/8859-15.TXT
