### ISSUE TITLE
Struct of Array C++ library

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos-sdk#185]
Using the struct of arrays pattern requires a constrained way of programming to maintain efficiency. It's unlikely that this optimization would pay off in arbitrary C++ outside of very restricted scenarios (e.g., a function-local array). It's also unlikely that the user experience of relying on a compiler optimization for this would be very good; there would be a lot of implicit, unwritten rules, and violating any of them would kill performance. Accordingly, providing a C++ library for this would give most of the benefit with a minimum of effort, and it would provide explicit source-level documentation that the pattern is being used, as well as help guard against certain type of misuse.

**Comment by johnwbyrd** [comment]
Possible inspiration, though it seems to be married to STL types: https://github.com/crosetto/SoAvsAoS
