### ISSUE TITLE
ninja clean doesn't clean mos-build external project

### ISSUE THREAD

**Issue by mysterymath** [llvm-mos/llvm-mos-sdk#20]
I've noticed that `ninja clean` will only clean the build artifacts from the outer project, not any of the target-specific files. This can make it difficult to test changes to the compiler, since it won't rebuilt the target files unless I completely remove them by hand.

**Comment by mysterymath** [comment]
Note: it does looks like I can just go into the `mos-build` directory itself and run `ninja clean`; it's maintained as a totally separate ninja environment. So there's an easy workaround at least.

**Comment by jackoalan** [comment]
I was actually looking into this yesterday.

I think this property is the way to go if we raise our CMake requirement to 3.15:
https://cmake.org/cmake/help/latest/prop_dir/ADDITIONAL_CLEAN_FILES.html

**Comment by jackoalan** [comment]
Fixed in 2099903
