### ISSUE TITLE
Add sections for the ram memory area when c-in-prg-ram is used

### ISSUE THREAD

**Issue by cogwheel** [llvm-mos/llvm-mos-sdk#216]
On NES mapper targets, when `c-in-prg-ram` is used, there are no sections that map into the RAM memory area. This makes (2 KiB - 2 pages) worth of RAM effectively unavailable for use without adding custom linker scripts.

Maybe there could sections like `.low_ram.(bss|data|noinit).*` that always map to the `ram` region? These could even be used by things like the neslib buffers and the software stack to leave more "user" ram available (and marginally simplify PRG-RAM banking)

**Comment by mysterymath** [comment]
By analogy these should just be called `.ram`; this was pretty much just a straight oversight. But yes, every other region has dedicated sections; RAM should too.

**Comment by mysterymath** [comment]
Fixed by #218.
