### ISSUE TITLE
Implement realloc

### ISSUE THREAD

**Issue by mrk-its** [llvm-mos/llvm-mos-sdk#22]
It would be great to have also `realloc` implemented, especially for small sizes of heap.
For example, I'm testing allocation using following rust code:

```
input.split("\n").map(|i| i.parse::<i16>().unwrap()).collect::<Vec<_>>();
```

and it fails trying to allocate memory for 2000 integers (4000 bytes total) having default heap size 4096 bytes.

It produces following chain of calls of rust allocator:

```
alloc(2) -> 0x520e
alloc(8) -> 0x5216
realloc(0x520e, 8) -> 0x5216
alloc(16) -> 0x5224
realloc(0x5216, 16) -> 0x5224
alloc(32) -> 0x523a
realloc(0x5224, 32) -> 0x523a
alloc(64) -> 0x5260
realloc(0x523a, 64) -> 0x5260
alloc(128) -> 0x52a6
realloc(0x5260, 128) -> 0x52a6
alloc(256) -> 0x532c
realloc(0x52a6, 256) -> 0x532c
alloc(512) -> 0x5432
realloc(0x532c, 512) -> 0x5432
alloc(1024) -> 0x5638
realloc(0x5432, 1024) -> 0x5638
alloc(2048) -> 0x0
realloc(0x5638, 2048) -> 0x0
PANIC!!!
```

So it starts with small memory allocated for vector and increases capacity as new data is added trying to realloc existing buffer. Default realloc implementation simply allocates new buffer and copies data - that's why there is not enough memory.

relloc would reduce heap fragmentation in such case and simply fit data in memory.

cc: @karunski

**Comment by karunski** [comment]
I think this is possible. You can assign to me.

**Comment by karunski** [comment]
@mrk-its  Please try the realloc implementation. It will realloc in the manner you describe.

**Comment by mrk-its** [comment]
@karunski thanks! will do that later today and let you know.

**Comment by mrk-its** [comment]
Works like a charm!:
```
heap bytes free: 4090 / 4096
alloc 2 -> 0x5998
realloc 0x5998 8 -> 0x5998
realloc 0x5998 16 -> 0x5998
realloc 0x5998 32 -> 0x5998
realloc 0x5998 64 -> 0x5998
realloc 0x5998 128 -> 0x5998
realloc 0x5998 256 -> 0x5998
realloc 0x5998 512 -> 0x5998
realloc 0x5998 1024 -> 0x5998
realloc 0x5998 2048 -> 0x5998
allocated, free: 2030
deallocated, free: 4090
```

**Comment by mrk-its** [comment]
@karunski one question: does your realloc impl support `shrinking` (new_size smaller than current allocation size)?

**Comment by karunski** [comment]
Currently it will not shrink an allocation. You just get back the original allocation.
