### ISSUE TITLE
cx16 kernal name confusion: cx16_k_savehl vs cbm_k_savehl

### ISSUE THREAD

**Issue by bcampbell** [llvm-mos/llvm-mos-sdk#242]
`cx16_k_savehl` is declared in `cx16.h` and implemented in `mos-platform/cx16/cx16_k_savehl.s`.

`cx16_k_savehl` is exported, but the actual label used on the routine is `cbm_k_savehl`. So when you try and link, it can't find it.

Also, the cx16 kernal docs use the name BSAVE instead (same entry address as SAVEHL: $FEBA). The cx16 [kernal docs](https://github.com/X16Community/x16-docs/blob/master/X16%20Reference%20-%2004%20-%20KERNAL.md#kernal-api-functions) claim BSAVE is a cx16-specific routine, but now I'm wondering if other commodore kernals (128/+4/etc) had it as SAVEHL?

**Comment by mysterymath** [comment]
@XarkLabs

**Comment by XarkLabs** [comment]
I will look into this.  This HL is like BSAVE, but without a two byte header IIRC...

**Comment by XarkLabs** [comment]
This cx16 call was previously undocumented and I was using internal name "savehl", now it is properly documented as BSAVE, so #243 renames llvm-mos-sdk cx16 function and vector to use documented name.

**Comment by bcampbell** [comment]
Ahh, thanks for that! Both for the fix and for casting some light on the history of it!
Much appreciated.

**Comment by XarkLabs** [comment]
My pleasure. Thanks for mentioning it (and also pointing out my "typo" in the older version).
