### ISSUE TITLE
bitrot in wiki porting page

### ISSUE THREAD

**Issue by bcampbell** [llvm-mos/llvm-mos-sdk#256]
I'm just dipping my toe into the porting process at the moment, using the excellent guide at https://llvm-mos.org/wiki/Porting

I've got as far as pasting my minimal `link.ld`, but when I get to the "Compiling: Second Attempt" section, I get:

```
$ mos-common-clang -o main -Os main.c
ld.lld: error: memory region 'c_readonly' not declared
ld.lld: error: memory region 'zp' not declared
ld.lld: error: memory region 'zp' not declared
ld.lld: error: memory region 'c_readonly' not declared
ld.lld: error: memory region 'c_readonly' not declared
ld.lld: error: memory region 'c_writeable' not declared
ld.lld: error: memory region 'c_writeable' not declared
ld.lld: error: memory region 'c_writeable' not declared
mos-common-clang: error: ld.lld command failed with exit code 1 (use -v to see invocation)
```

I'm guessing these names were added to the `c.ld` setup after the porting guide was written?
I suspect I can muddle my way through getting it building, but I don't think I know enough to attempt to update the wiki page...

**Comment by bcampbell** [comment]
It wasn't updating the wiki I didn't know about - it's the linker scripting.
I'm just blundering about here, so I don't think I'm the right person to fix the page without making it much much worse :-)

**Comment by asiekierka** [comment]
The linker scripts have been updated by someone on 26th January 2024. As such, I think this issue can be closed?
