### ISSUE TITLE
Implement libm min and max functions

### ISSUE THREAD

**Issue by mrk-its** [llvm-mos/llvm-mos-sdk#299]
In RUST cast from float to int (with `as` keyword) is saturating operation: https://doc.rust-lang.org/reference/expressions/operator-expr.html#numeric-cast

and for now it generates following error:

```
LLVM ERROR: unable to legalize instruction: %22:_(s32) = G_INTRINSIC intrinsic(@llvm.fptosi.sat), %8:_(s32) (in function: main)
```

**Comment by mlund** [comment]
Does this involve adding the functions to `common/include/math.h`, and add a new corresponding `math.cpp` file to produce a static library `m`? Also, are comparison operators already available for floats?

**Comment by mysterymath** [comment]
> Does this involve adding the functions to `common/include/math.h`, and add a new corresponding `math.cpp` file to produce a static library `m`? Also, are comparison operators already available for floats?

Yes and yes.

**Comment by mlund** [comment]
Here's a preliminary implementation. Not entirely sure if this should be split into it's own static library with `add_platform_library(m, ...)`?.
https://github.com/llvm-mos/llvm-mos-sdk/compare/main...mlund:llvm-mos-sdk:fminmax?expand=1

**Comment by mysterymath** [comment]
> Here's a preliminary implementation. Not entirely sure if this should be split into it's own static library with `add_platform_library(m, ...)`?. https://github.com/llvm-mos/llvm-mos-sdk/compare/main...mlund:llvm-mos-sdk:fminmax?expand=1

Separate libm provides no benefit toa modern static-linking-only toolchain; best not to follow.

You will need to account for NaN: min and max have to return the other argument if one is NaN.
