### ISSUE TITLE
mos-sim crash

### ISSUE THREAD

**Issue by mrk-its** [llvm-mos/llvm-mos-sdk#307]
attached [day05.zip](https://github.com/llvm-mos/llvm-mos-sdk/files/14319519/day05.zip) crashes mos-sim:

$ mos-sim day05
PART1: BWNCQRMDB
Aborted (core dumped)

it is produced by last test version of `rust-mos`

**Comment by mysterymath** [comment]
This isn't a crash in `mos-sim`; it's calling `abort()` intentionally. This occurs whenever a write to 0xFFF7 occurs; it's part of the protocol used to pass results out of the simulator.

**Comment by mrk-its** [comment]
Ok, so the issue is different - I need to investigate why abort is called by this rust program now (it was working fine on my older rust-mos builds)
