### ISSUE TITLE
realloc returns memory overlapping with other memory block

### ISSUE THREAD

**Issue by mrk-its** [llvm-mos/llvm-mos-sdk#314]
Following rust program [day05.zip](https://github.com/llvm-mos/llvm-mos-sdk/files/14319519/day05.zip) crashes because of heap memory corruption.

I'm attaching small  [python script ](https://github.com/llvm-mos/llvm-mos-sdk/files/14323593/realloc.zip) with sequence of `malloc` / `realloc` / `free` calls logged from above program, looking for block overlaps. It looks that one of the `realloc` calls returns region overlapping with other block allocated earlier (probably because of https://github.com/llvm-mos/llvm-mos-sdk/pull/292) 

Replacing `realloc` with `alloc` + `memcpy` makes this program working fine. It also works fine on older SDK with previous malloc implementation.

**Comment by mysterymath** [comment]
Thanks, I expected that something would break after a big malloc rewrite; looks like this is it. I'll go through and debug this.

**Comment by mysterymath** [comment]
Could you make a `.ll` version of this that I could compile against a different version of `realloc`? I've got a bunch of tracing in the SDK that would be helpful.

Failing that, the output of this recompiled against an SDK with `MALLOC_TRACE` set to 1 in`malloc.cc` would be helpful

**Comment by mrk-its** [comment]
Debug build: [day05-0cd8b2583aaf17c6.zip](https://github.com/llvm-mos/llvm-mos-sdk/files/14329248/day05-0cd8b2583aaf17c6.zip) 

Release build: [day05-fa63e06c3e659ee6.zip](https://github.com/llvm-mos/llvm-mos-sdk/files/14329258/day05-fa63e06c3e659ee6.zip)
