### ISSUE TITLE
adc() and sbc() BCD bugs in fake6502.c

### ISSUE THREAD

**Issue by barrym95838** [llvm-mos/llvm-mos-sdk#33]
It seems to be a minor or possibly insignificant point in the context of this impressive development, but the simulated adc() and sbc() functions in fake6502.c have buggy BCD correction code.  I offered public domain replacements at:
http://forum.6502.org/viewtopic.php?p=37758#p37758
which you are politely invited to consider.

**Comment by mysterymath** [comment]
Thanks! I've added these to our copy of fake6502.c in 466d5850.
