### ISSUE TITLE
[PC ENGINE] Wrong joypad button mask

### ISSUE THREAD

**Issue by Ced2911** [llvm-mos/llvm-mos-sdk#335]
The button mask for right and down button is inverted.
According to https://github.com/pce-devel/huc/blob/a627890f96b45a8dcf8b994ac9eb04bd048a0992/include/huc/joypad.asm#L15
KEY_RIGHT should be 0x20
KEY_DOWN should be 0x40

**Comment by mysterymath** [comment]
@asiekierka
