### ISSUE TITLE
Linker script for a simple ROM?

### ISSUE THREAD

**Issue by atirut-w** [llvm-mos/llvm-mos-sdk#40]
I am making a custom BIOS and I cannot seem to figure out how to make the linker put codes and initialized data(strings, etc.) in the area starting from $F000

**Comment by mysterymath** [comment]
The easiest way to do this is to use a [MEMORY](https://sourceware.org/binutils/docs/ld/MEMORY.html) command:
```
MEMORY {
  ram (rw) : ORIGIN = 0xf000, LENGTH = <However much room you have>
}
```

If a MEMORY command is present, then the linker will try to place each C section into a matching memory region, based on the attributes. `rw` says "place both read-only and writable sections here", so it matches everything, and the compiler will begin assigning code and data at 0xf000.

We use standard GCC-compatible linker scripts, so there's a ton of information out there on the web on how to set up linker scripts for embedded targets (which the 6502 definitely is, by modern standards). The LD manual (linked above) is a good place to start, aside from the usual StackOverflow.

**Comment by atirut-w** [comment]
> MEMORY {
>   ram (rw) : ORIGIN = 0xf000, LENGTH = <However much room you have>
> }

That's what I did, and the results are very weird.

If I compile this code, it comes out fine and runs just fine:
```c
// void print(const char *str) {
//     while (*str) {
//         *(char *)0x2ff = *str;
//     }
// }

void main() {
    const char *cur = "Hello, World!";
    // print(cur);
    while (*cur)
        *(char *)0x2ff = *cur++;
    while (1) {}
}
```
![Screenshot_20220602_164602](https://user-images.githubusercontent.com/25323231/171603493-b7008259-8fee-42b7-a7f2-eefd222ce8e9.png)

However if I change it to use the print function instead, the string seems to disappear from the resulting binary and the code only outputs the first character before hanging up
![Screenshot_20220602_165620](https://user-images.githubusercontent.com/25323231/171605325-9d85119e-111d-406e-aaaa-2dfdbc8e6849.png)

**Comment by atirut-w** [comment]
I think this might be a problem with the "optimizer"? The string reappears if I remove the `-Os` flag, although it causes the compiled code to hang before even doing anything.

**Comment by atirut-w** [comment]
Should have also included when I was replying:
```ld
MEMORY {
    /* ram (w) : ORIGIN = 0x1000, LENGTH = 0xe000 */
    ram (rw) : ORIGIN = 0xf000, LENGTH = 0x0ffc
}

SECTIONS {
    INCLUDE c.ld
}

__rc0 = 0x05;
__rc1 = 0x06;
__rc2 = 0x07;
__rc3 = 0x08;
__rc4 = 0x09;
__rc5 = 0x0a;
__rc6 = 0x0b;
__rc7 = 0x0c;
__rc8 = 0x0d;
__rc9 = 0x0e;
__rc10 = 0x0f;
__rc11 = 0x10;
__rc12 = 0x11;
__rc13 = 0x12;
__rc14 = 0x13;
__rc15 = 0x14;

OUTPUT_FORMAT {
    FULL(ram)
    SHORT(_start)
}
```

**Comment by atirut-w** [comment]
Turns out, I have to decare my pointer to the serial terminal address as volatile otherwise the compiler will do weird stuff to it. Closed, I guess?

**Comment by atirut-w** [comment]
@mysterymath I found a problem with your suggestion of putting everything into the ROM. Problem is, ROMs are read-only and the compiler seems to allocate some struct variables in the same area as ROM in your suggested configuration. This caused some data to disappear. Any other alternative configurations?
