### ISSUE TITLE
Relocatable binary format?

### ISSUE THREAD

**Issue by atirut-w** [llvm-mos/llvm-mos-sdk#41]
When compiling codes, the resulting ELF binary does not seem to have any relocation data. This means if any 6502 OS wants to do multitasking, LLVM-MOS ELF is not an option. While there are other compilers like CC65 supports outputting to O65 relocatable format, the performance of the compiled codes just sucks in general.

Being able to have both LLVM's awesome optimization and being able to relocate codes would be very nice.

**Comment by mysterymath** [comment]
The linker can generate relocatable output files upon request via the `-r` flag. You can use this with the compiler driver via `clang ... -Wl,-r ...`.

I looked into this only a little, but it seems ELF isn't really suitable as a relocation format for use on an actual 6502 system. It uses 32-bit integers freely, which blows out the sizes of things well beyond what's reasonable. Converting from ELF to O65 (or a custom format) might be feasible, but there may be ELF features that don't map cleanly onto O65. It'd then be a matter of trying to make sure that the linker never incidentally output such features.

**Comment by mysterymath** [comment]
It looks like this isn't exactly what you're asking for; `-r` is really intended for "partial linking", where the result is used as an input to a futher link action.

`-q` is exactly what you described: it just leaves the relocations in the output exectuable.
