### ISSUE TITLE
Unable to embed character ROM for NES.

### ISSUE THREAD

**Issue by CalinLeafshade** [llvm-mos/llvm-mos-sdk#47]
I've written a simple test program for the NES and I can build and link it fine until I try to include a character rom.

I added a .s file with the following: 

```
.section .chr_rom
  .incbin "tileset.chr"
```

and included it as part of the build script:

```
./llvm-mos/bin/mos-nes-nrom-128-clang -Os -o climbr.nes main.c chars.s
```

However the linker gives the following error:

```
ld.lld: warning: ignoring memory region assignment for non-allocatable section '.chr_rom'
ld.lld: warning: ignoring memory region assignment for non-allocatable section '.vector'
```

And doesn't include either the character rom or the starting vector.

What am I doing wrong?

**Comment by CalinLeafshade** [comment]
It seems like the chr_rom section needs to marked as "keep" or it's collected by gc-sections

nes-nrom.ld
```
  .chr_rom : { KEEP(*(.chr_rom)) } >chr_rom
```

Is this the correct approach?

**Comment by mysterymath** [comment]
So, there's some boilerplate that needs to be included in section definitions:
`.section .chr_rom,"aR"` should work.

The "a" marks the section as allocatable, that is, that it should take up memory at runtime. This is opposed to things like symbols or debug information. The "R" marks the section as "retained", which means not to garbage collect it, even if none of the symbols it defines are ever referenced.

I think you're right though; we probably should have the data sections be KEEP, which essentially sets "R" on the sections automatically. The layout of NES ROM sections are fixed, so it doesn't make sense to GC things out of them.

**Comment by CalinLeafshade** [comment]
That all seems to work ok now.
Thanks for your comment.

**Comment by mysterymath** [comment]
I took a look into this; we're constrained by GNU ld behavior here, so we can't make "a" the default. I added a FAQ entry about this on the Wiki. I've also made the ROM sections KEEP in the NES linkers script, which solves that half of the issue at least.
