### ISSUE TITLE
How to build the SDK with cmake on Windows?

### ISSUE THREAD

**Issue by smuehlst** [llvm-mos/llvm-mos-sdk#7]
I downloaded the most recent llvm-mos build from https://github.com/llvm-mos/llvm-mos/releases/tag/llvm-mos-windows-main, and I tried to adapt the Linux instructions to build the SDK to Windows. But this fails quickly:

```
E:\Users\stm\Documents\GitHub\llvm-mos-sdk [winbuild]> & "C:\Program Files\CMake\bin\cmake.exe" -DLLVM_MOS=E:/Users/stm/local/llvm-mos/bin -G Ninja -B build
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The ASM compiler identification is unknown
-- Didn't find assembler
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_ASM_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "ASM" or the CMake cache entry CMAKE_ASM_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Warning: Did not find file Compiler/-ASM
-- Configuring incomplete, errors occurred!
See also "E:/Users/stm/Documents/GitHub/llvm-mos-sdk/build/CMakeFiles/CMakeOutput.log".
See also "E:/Users/stm/Documents/GitHub/llvm-mos-sdk/build/CMakeFiles/CMakeError.log".
```
I'm not very experienced with CMake, but it looks to me like it is not specified that this is a cross-compilation, and therefore CMake is looking for a C compiler for the current platform, e.g. for a Windows C compiler here.

**Comment by greg-king5** [comment]
The command-line option `-G Ninja` makes CMake look for POSIX compilers in standard POSIX places.

What programming environment are you trying to use?

**Comment by johnwbyrd** [comment]
Welcome to the project, greg-king5.

**Comment by johnwbyrd** [comment]
Try setting CMAKE_C_COMPILER and CMAKE_CXX_COMPILER to the path of the LLVM-MOS compiler.

**Comment by smuehlst** [comment]
> What programming environment are you trying to use?

At the moment I'm not trying to use a specific programming environment, I just want to build the SDK on Windows.

**Comment by AGPX** [comment]
I want to add that CMake also ask for a CMAKE_RC_COMPILER which is absent in the llvm-mos but you can set it to the file clang++.exe too (after all, RC are not used at all and so it's not a problem).
