### ISSUE TITLE
"Common ELF" target

### ISSUE THREAD

**Issue by atirut-w** [llvm-mos/llvm-mos-sdk#76]
Basically the common target but with a linker script that outputs a relocatable ELF file. May be useful for custom 8-bit OSes, patching stuff(ROMs, disk images, etc.), or some other stuff.

**Comment by mysterymath** [comment]
Most ELF executables aren't actually relocatable; you can thank virtual memory for that. Accordingly, there isn't actually anything in the linker script that can cause the linker to issue a relocatable file; this is completely controlled by the `-q` and `-r` linker options.

Accordingly, it's hard (at least for me) to envision what should actually go into something like this without a more concrete use case. SDKs are a good place to codify existing practice, so if you want to whip up an OS, go for it, and we can try to abstract away the commonalities to all such approaches later.

**Comment by atirut-w** [comment]
One of my planned use cases is relocatable kernel. It's for a project of mine that's been on hold for an emulated 6502 arch that have an MMU that can remap the memory in 4KB chunks.

The bootloader wouldn't need to be relocatable since it's loaded in from disk at a fixed location, but considering how the size of the bootloader can vary, the kernel have to be in a relocatable format(not necessarily ELF).

**Comment by atirut-w** [comment]
@mysterymath can this be reopened as just a request for non-relocatable ELF and delegate the relocation stuff to user-written build scripts?

**Comment by mysterymath** [comment]
All builds generate non relocatable ELF by default. If the target executable is foo, the corresponding ELF file is foo.elf, in the same directory.

**Comment by atirut-w** [comment]
I know, but not having to write a linker script and setting `CMAKE_TRY_COMPILE_TARGET_TYPE` on ELF projects would be nice.

**Comment by mysterymath** [comment]
I think supporting this will would bear further design work, and this would be a project that would likely span the compiler, linker, and SDK. The compiler driver is set up to mandate the use of a linker script, and we haven't paid much attention to the state of the implicit defaults in LLD.

It's an interesting project to be sure, but not one I'm likely to take on in the near future. I'm definitely open to this as a contribution, but I'll warn that whoever builds thus would either start with, or end up with, a fairly thorough understanding of compiler drivers, ELF, and linker.

Still, I don't think it's actually that much work end to end; the difficulty is in figuring out what works today, what doesn't work, how to fix it, and how to make those fixes compatible with the existing SDK. Off the top of my head, the way we construct init and fini sections would likely need to dramatically change.

**Comment by johnwbyrd** [comment]
It is redundant to say that you want to create a "relocatable ELF file".  Most ELF files, including the ones emitted by the llvm-mos linker, are relocatable, until the stripping step that emits a binary by burning the relocations in.  It would be wiser to try to create an ELF loader for 6502, that can parse ELF files well enough to relocate them on load.  See also the OUTPUT_FORMAT directive, which defaults to ELF, but is commonly set to binary formats in the SDK.

**Comment by atirut-w** [comment]
Isn't it just the common target but with a default linker script anyway? And since enabling relocation data is literally just one flag away, we can leave that to the users.

**Comment by mysterymath** [comment]
No, having a runnable ELF binary involves cooperation between the C runtime and the ELF loader, with communication taking place via the ELF headers. Our current runtime model doesn't really set up those headers, and our C runtime hasn't really been built to make sure the right routines are available under the right default symbol names.
