### ISSUE TITLE
Place to ask questions about the compiler/assembler?

### ISSUE THREAD

**Issue by Andrew900460** [llvm-mos/llvm-mos-sdk#97]
**Right off the bat, I know this is definately not the place to ask such things, and I will delete this as soon as possible.**

But I would like to know if there is a place to ask questions about nuances with the compiler/assembler, because I am also fairly new to the llvm-compiler system. (I have not seen any info on the website of good places to go to talk about the compiler)

Briefly, I am trying to write an inline assembly function for reading controller info for the NES. I am getting issues with how it tries to handle asm lables. I could do:
```
asm("myLabel:")
// some other stuff
asm("bcc myLabel")
```
This works fine, but then if I try to call the function, it gets a compiler error due to the lable being in 2 places. To be clear, I am actually using Compiler Explorer to test all this, and I am gettig the error on there.

Also, I've been trying to follow the guides on the llvm-mos.org website for doing inline assembly, but I am still having another issue related to this function I'm talking about not actually returning anything. Due to how the "ReadJoypad" function works, it never needs to access any variables, but it does need to store the result in a variable. And I'm not sure If I understood what I'm supposed to tell the compiler to give the correct output.

**Comment by mysterymath** [comment]
To answer you question about where to answer questions, the best place is on our Slack channel: https://join.slack.com/t/llvm-mos/shared_invite/zt-t88fyh4i-EGCLe~MSlHdz3~h~yYHgFA. This is also linked to from the homepage of the llvm-mos.org wiki.

Unfortunately, we don't yet support asm goto, and we really can't until someone gets around to implementing it in the GlobalISel backend, which we're using. I could probably do this with some considerable difficulty, but in cases like this, it's usually better to just write the whole routine in assembly and call it from C.
